name: Release
on:
 release:
   types: [published]

jobs:
  build:
    name: Release Notifier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release Notify Git Actions GH Action
        uses: actions/checkout@v2
        with:
          repository: PayCertify/release-notify-git-actions
          token: ${{ secrets.ACTIONS_TOKEN }}
          path: ./.github/actions/release-notify

      - name: Install dependencies
        run: cd ./.github/actions/release-notify && npm i

      - name: Release Notify Git Actions
        uses: ./.github/actions/release-notify
        id: releaseStep
        with:
          github-token: ${{ secrets.ACTIONS_TOKEN }}
          slackbot-token: x
          slack-conversation-id: elias@paycertify.com
          sendgrid-token: ${{ secrets.SENDGRID_RELEASE_NOTIFY_TOKEN }}
          email-recipients: elias@paycertify.com,denis.toledo@paycertify.com
      