name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm i
      - uses: ./
        with:
            repository: PayCertify/release-notify-git-actions
      - uses: ./
        with:
            owner: eliasmelgaco
            repo: release-notify-git-actions
      - uses: ./
        with:
            owner: eliasmelgaco
            repo: release-notify-git-actions
            excludes: prerelease, draft