name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Release Notify Git Actions
        - uses: ./
          with:
            repository: PayCertify/release-notify-git-actions
          with:
            github-token: '7dd6a3cb737053d1f74c30082070a9509d357bdc'
            slackbot-token: 'x'
            slack-conversation-id: 'elias@paycertify.com'
      